export const STANDING_ORDER_CREATE_REQUEST = 'STANDING_ORDER_CREATE_REQUEST'
export const STANDING_ORDER_CREATE_SUCCESS = 'STANDING_ORDER_CREATE_SUCCESS'
export const STANDING_ORDER_CREATE_FAIL = 'STANDING_ORDER_CREATE_FAIL'
export const STANDING_ORDER_CREATE_RESET = 'STANDING_ORDER_CREATE_RESET'

export const STANDING_ORDER_DETAILS_REQUEST = 'STANDING_ORDER_DETAILS_REQUEST'
export const STANDING_ORDER_DETAILS_SUCCESS = 'STANDING_ORDER_DETAILS_SUCCESS'
export const STANDING_ORDER_DETAILS_FAIL = 'STANDING_ORDER_DETAILS_FAIL'

export const STANDING_ORDER_UPDATE_REQUEST = 'STANDING_ORDER_UPDATE_REQUEST'
export const STANDING_ORDER_UPDATE_SUCCESS = 'STANDING_ORDER_UPDATE_SUCCESS'
export const STANDING_ORDER_UPDATE_FAIL = 'STANDING_ORDER_UPDATE_FAIL'
export const STANDING_ORDER_UPDATE_RESET = 'STANDING_ORDER_UPDATE_RESET'


export const STANDING_ORDER_LIST_REQUEST = 'STANDING_ORDER_LIST_REQUEST'
export const STANDING_ORDER_LIST_SUCCESS = 'STANDING_ORDER_LIST_SUCCESS'
export const STANDING_ORDER_LIST_FAIL = 'STANDING_ORDER_LIST_FAIL'

export const STANDING_ORDER_DELETE_REQUEST = 'STANDING_ORDER_DELETE_REQUEST'
export const STANDING_ORDER_DELETE_SUCCESS = 'STANDING_ORDER_DELETE_SUCCESS'
export const STANDING_ORDER_DELETE_FAIL = 'STANDING_ORDER_DELETE_FAIL'